# version: '3.8'

# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb_container
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db
#     restart: always

#   fastapi:
#     build:
#       context: .  # Path to the directory containing your Dockerfile
#     container_name: fastapi_container
#     environment:
#       MONGODB_URL: "mongodb+srv://slasher190:rYHs3vSfnX0yCWcv@cluster0.5awar.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mongodb
#     restart: always

# volumes:
#   mongo_data:
#     driver: local
version: '3.8'

services:
  fastapi:
    build:
      context: .
    container_name: fastapi_container
    environment:
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - "8000:8000"
    restart: always
